### ISSUE TITLE
Clarification about Storage Partitioning and phasing out of third-party cookies

### ISSUE THREAD

**Issue by nir-walkme** [wanderview/quota-storage-partitioning#5]
Hi

Back in July, Google [announced](https://blog.google/products/chrome/update-testing-privacy-sandbox-web/) that they intend to begin phasing out third-party cookies in Chrome in the **second half of 2024**.

Meanwhile, last week, a new [update was published](https://developer.chrome.com/en/blog/storage-partitioning-dev-trial/) on Storage Partitioning.
Per my understanding of this update:
1. Storage Partitioning does not disable third party cookies, but it does makes them inoperable for cross-domain tracking.
2. Storage Partitioning will start to be rolled out to users in **early 2023**.

So these two separate announcements seems to contradict each other. While Storage Partitioning does not disable third-party cookies, it does disable the primary use of third-party cookies a year before the 2024 deadline.

Could you please clarify this contradiction?

**Comment by wanderview** [comment]
There are different kinds of storage in the browser.  Cookies are sent with network requests by default and can be accessed by javascript using the navigator.cookies API.  Other types of storage include things like localstorage, IndexedDB, CacheStorage, ServiceWorker, etc.

The update you reference only affects the non-cookie types of storage.  Cookie storage is not affected at all.

(Note, this distinction is admittedly confusing because browsers use the word "cookie" in UI settings to refer to all storage.  In web specifications, however, these storage types are always distinguished and separate.)

Hopefully this clears up the confusion.  Cookies will not be changed by storage partitioning.  Only non-cookie storage will be changed.
